/**
 * Generated by scripts/generate-openapi.mjs from public/api/messaging-sms.yaml.
 * Do not edit: change the spec and run `npm run generate:api`.
 */
import type { ApiSpec } from "@/lib/openapi";

export const spec: ApiSpec = {
  "title": "Messaging API",
  "summary": "Send SMS and MMS, and receive inbound messages on a webhook.",
  "description": "Send text and picture messages from any number you have SMS-enabled in the portal, and receive replies on a webhook you register against that number. Requests carry two credentials, both issued from Company Settings → API Keys in the [Wiretap Portal](https://portal.wiretaptelecom.com).",
  "version": "1.0.0",
  "baseUrl": "https://sms.wiretaptelecom.com/smsapis",
  "security": [
    {
      "id": "BearerAuth",
      "kind": "bearer",
      "name": "Authorization",
      "description": "The **Bearer Token** from Company Settings → API Keys, sent as `Authorization: Bearer <token>`."
    },
    {
      "id": "ApiKeyQuery",
      "kind": "query",
      "name": "apikey",
      "description": "The **Auth Token** from the same screen, sent as the `apikey` query parameter. It is a distinct value from the bearer token."
    }
  ],
  "operations": [
    {
      "id": "SendSMS",
      "slug": "send-sms",
      "kind": "operation",
      "method": "post",
      "path": "/SendSMS",
      "summary": "Send an SMS or MMS",
      "description": "Sends one message to one or more mobile numbers. Supplying `mediaUrls` turns the message into an MMS, which bills at the MMS rate. The sending number has to be SMS-enabled under Core-SMS → Manage Numbers and covered by a registered 10DLC campaign, or carriers will block the traffic.",
      "responses": [
        {
          "status": "200",
          "description": "The gateway accepted the request. Read `schema.resultResponses` for the outcome of each recipient, since one bad number does not fail the whole batch.",
          "schema": {
            "type": "object",
            "properties": [
              {
                "name": "success",
                "required": false,
                "schema": {
                  "type": "boolean",
                  "description": "Whether the gateway accepted the request as a whole.",
                  "example": true
                }
              },
              {
                "name": "reason",
                "required": false,
                "schema": {
                  "type": "string",
                  "description": "Short result code for the request.",
                  "example": "SUCCESS"
                }
              },
              {
                "name": "detail",
                "required": false,
                "schema": {
                  "type": "string",
                  "description": "Longer description of the reason.",
                  "example": "SUCCESS"
                }
              },
              {
                "name": "schema",
                "required": false,
                "schema": {
                  "type": "object",
                  "description": "The message as the gateway recorded it, with a result per recipient.",
                  "properties": [
                    {
                      "name": "referenceId",
                      "required": false,
                      "schema": {
                        "type": "string",
                        "description": "The id tracking the message. If you supplied one in the request it repeats here.",
                        "example": "h4Tk44ks21iR"
                      }
                    },
                    {
                      "name": "from",
                      "required": false,
                      "schema": {
                        "type": "string",
                        "description": "The number the message was sent from.",
                        "example": "14055551234"
                      }
                    },
                    {
                      "name": "text",
                      "required": false,
                      "schema": {
                        "type": "string",
                        "description": "The body that was sent.",
                        "example": "This is a test"
                      }
                    },
                    {
                      "name": "resultResponses",
                      "required": false,
                      "schema": {
                        "type": "array",
                        "description": "One entry per recipient.",
                        "items": {
                          "type": "object",
                          "properties": [
                            {
                              "name": "to",
                              "required": false,
                              "schema": {
                                "type": "string",
                                "description": "A number that received the message.",
                                "example": "13055551234"
                              }
                            },
                            {
                              "name": "status",
                              "required": false,
                              "schema": {
                                "type": "string",
                                "description": "The outcome for that number.",
                                "example": "SUCCESS"
                              }
                            }
                          ]
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "status": "400",
          "description": "Bad input parameter, or credentials the gateway would not take. The body is the same envelope as a success, with `success` false and a `reason` naming the problem.",
          "schema": {
            "type": "object",
            "properties": [
              {
                "name": "success",
                "required": false,
                "schema": {
                  "type": "boolean",
                  "description": "False on every rejected request.",
                  "example": false
                }
              },
              {
                "name": "reason",
                "required": false,
                "schema": {
                  "type": "string",
                  "description": "Short code for what went wrong, such as `NOT_AUTHORIZED`.",
                  "example": "NOT_AUTHORIZED"
                }
              },
              {
                "name": "detail",
                "required": false,
                "schema": {
                  "type": "string",
                  "description": "Longer description of the reason.",
                  "example": "NOT_AUTHORIZED"
                }
              }
            ]
          }
        }
      ],
      "requestBody": {
        "description": "The message to send.",
        "required": true,
        "schema": {
          "type": "object",
          "properties": [
            {
              "name": "from",
              "required": true,
              "schema": {
                "type": "string",
                "description": "The number the message is sent from, in E.164 without the plus. It must be SMS-enabled on your account.",
                "example": "14055551234"
              }
            },
            {
              "name": "to",
              "required": true,
              "schema": {
                "type": "array",
                "description": "The numbers receiving the message, in E.164 without the plus. Messages sent in any other format will not be delivered.",
                "example": [
                  "13055551234",
                  "18135551234"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            {
              "name": "text",
              "required": true,
              "schema": {
                "type": "string",
                "description": "The body of the message.",
                "example": "This is a test"
              }
            },
            {
              "name": "mediaUrls",
              "required": false,
              "schema": {
                "type": "array",
                "description": "Publicly reachable URLs of the images to attach. Supplying this field converts the message to an MMS, and additional messaging rates apply.",
                "example": [
                  "https://wiretaptelecom.com/assets/img/logo.png"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            {
              "name": "referenceId",
              "required": false,
              "schema": {
                "type": "string",
                "description": "Your own id for the message. If you send one it is echoed back in the response, which is how you tie a result to a record on your side.",
                "example": "iosd84ndi9"
              }
            }
          ]
        }
      }
    }
  ],
  "webhooks": [
    {
      "id": "inboundMessage",
      "slug": "inbound-message",
      "kind": "webhook",
      "method": "post",
      "path": "",
      "summary": "Inbound message",
      "description": "We POST this body to the URL you register on a number in the portal, under Core-SMS → Manage Numbers → Receive to Webhook API. The URL is set per number, so different numbers can land in different systems. Return 200 to acknowledge the message.",
      "responses": [
        {
          "status": "200",
          "description": "Your server returns this code if it accepts the callback."
        }
      ],
      "requestBody": {
        "description": "The message that arrived on your number.",
        "required": true,
        "schema": {
          "type": "object",
          "properties": [
            {
              "name": "from",
              "required": true,
              "schema": {
                "type": "string",
                "description": "The number that sent the message.",
                "example": "14055551234"
              }
            },
            {
              "name": "to",
              "required": true,
              "schema": {
                "type": "array",
                "description": "Your numbers that received it.",
                "example": [
                  "13055551234"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            {
              "name": "text",
              "required": true,
              "schema": {
                "type": "string",
                "description": "The body of the message.",
                "example": "This is a test"
              }
            },
            {
              "name": "mediaUrls",
              "required": false,
              "schema": {
                "type": "array",
                "description": "URLs of any images attached to the message.",
                "example": [
                  "https://wiretaptelecom.com/assets/img/logo.png"
                ],
                "items": {
                  "type": "string"
                }
              }
            },
            {
              "name": "referenceId",
              "required": false,
              "schema": {
                "type": "string",
                "description": "Our id for the message.",
                "example": "iosd84ndi9"
              }
            }
          ]
        }
      }
    }
  ],
  "specPath": "/api/messaging-sms.yaml"
};
