/**
 * Generates src/lib/us-map.ts: a lower-48 outline path plus projected screen
 * coordinates for our points of presence and the demo origin cities.
 *
 * Only needs re-running if the regions in POPS change.
 *
 *   curl -L -o states-10m.json \
 *     https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json
 *   npm run generate:map -- states-10m.json
 */
import { readFileSync, writeFileSync } from "node:fs";
import { geoAlbers, geoPath } from "d3-geo";
import { feature, merge, mesh } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";

const WIDTH = 720;
const HEIGHT = 440;
// Tuned by eye: coastlines, the Great Lakes, and Florida all stay legible at
// render size while the two paths together come to roughly 12 kB of source.
const MIN_WEIGHT = Number(process.argv[3] ?? 8e-3);

const raw = JSON.parse(readFileSync(process.argv[2] ?? "states-10m.json", "utf8"));

// Drop Alaska, Hawaii, and the territories: we sell the continental lower 48,
// and insets would imply coverage we do not offer.
const EXCLUDE = new Set(["02", "15", "60", "66", "69", "72", "78"]);
raw.objects.states.geometries = raw.objects.states.geometries.filter(
  (g) => !EXCLUDE.has(String(g.id).padStart(2, "0"))
);

const topology = simplify(presimplify(raw), MIN_WEIGHT);
const statesObject = topology.objects.states;

const lower48 = merge(topology, statesObject.geometries);
const interior = mesh(topology, statesObject, (a, b) => a !== b);

const projection = geoAlbers().fitSize([WIDTH, HEIGHT], lower48);
// Integer precision: at 720px across, a tenth of a pixel is invisible.
const path = geoPath(projection).digits(0);

const outline = path(lower48);
const borders = path(interior);

const project = ([lon, lat]) => {
  const [x, y] = projection([lon, lat]);
  return [Number(x.toFixed(1)), Number(y.toFixed(1))];
};

// Regions match the components published on status.wiretaptelecom.com.
//
// ATL1 and ATL2 are separate buildings a few miles apart. At this scale a mile
// is a quarter of a pixel, so their true positions land inside a single marker.
// `nudge` pushes the pair apart in screen space, symmetrically about the real
// coordinate, so the map shows two facilities without relocating either city.
const pops = [
  {
    id: "atl1",
    region: "atl",
    city: "Atlanta",
    label: "ATL1",
    at: [-84.388, 33.749],
    nudge: [-13, -7],
  },
  {
    id: "atl2",
    region: "atl",
    city: "Atlanta",
    label: "ATL2",
    labelBelow: true,
    at: [-84.388, 33.749],
    nudge: [13, 7],
  },
  { id: "mia", region: "mia", city: "Miami", label: "MIA", at: [-80.191, 25.761] },
  { id: "kan", region: "kan", city: "Kansas City", label: "KAN", at: [-94.578, 39.1] },
];

const origins = [
  { city: "Seattle, WA", at: [-122.332, 47.606], pop: "kan" },
  { city: "Boston, MA", at: [-71.058, 42.36], pop: "atl2" },
  { city: "Los Angeles, CA", at: [-118.243, 34.052], pop: "kan" },
  { city: "Tampa, FL", at: [-82.458, 27.947], pop: "mia" },
  { city: "Denver, CO", at: [-104.99, 39.739], pop: "kan" },
  { city: "Charlotte, NC", at: [-80.843, 35.227], pop: "atl2" },
  { city: "Austin, TX", at: [-97.743, 30.267], pop: "kan" },
  { city: "Columbus, OH", at: [-82.999, 39.961], pop: "atl1" },
];

const fmt = (list) =>
  list
    .map((item) => {
      const [px, py] = project(item.at);
      const [dx, dy] = item.nudge ?? [0, 0];
      const rest = Object.entries(item)
        .filter(([k]) => k !== "at" && k !== "nudge")
        .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
        .join(", ");
      const round = (n) => Number(n.toFixed(1));
      return `  { ${rest}, x: ${round(px + dx)}, y: ${round(py + dy)} },`;
    })
    .join("\n");

const out = `/**
 * Generated by scripts/generate-us-map.mjs from the us-atlas@3 states-10m topology,
 * simplified, then projected with d3-geo's Albers conic and fitted to the
 * viewBox below. Alaska, Hawaii, and the territories are excluded: we sell the
 * lower 48. Coordinates are screen space, already projected, so no geographic
 * math ships to the browser.
 */

export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};

/** Filled silhouette of the continental United States. */
export const US_OUTLINE =
  "${outline}";

/** Interior state boundaries, meshed so shared edges are drawn once. */
export const US_STATES =
  "${borders}";

export type Pop = {
  id: string;
  /** Facilities sharing a region fail over to another region, not to each other. */
  region: string;
  city: string;
  label: string;
  /** Set where a neighboring marker's label would otherwise collide. */
  labelBelow?: boolean;
  x: number;
  y: number;
};

export const POPS: Pop[] = [
${fmt(pops)}
];

export type Origin = { city: string; pop: string; x: number; y: number };

export const ORIGINS: Origin[] = [
${fmt(origins)}
];
`;

writeFileSync("src/lib/us-map.ts", out, "utf8");
console.log(`outline: ${(outline.length / 1024).toFixed(1)} kB`);
console.log(`borders: ${(borders.length / 1024).toFixed(1)} kB`);
console.log("wrote src/lib/us-map.ts");
